CREATE TABLE EMPLEADO(
ID NUMBER AUTO_INCREMENT,
NOMBRE VARCHAR(30),
NRO_OFICINA NUMBER,
FECHA_ALTA DATE,
OBSERVACIONES VARCHAR(30)
);

INSERT INTO EMPLEADO (ID,NOMBRE,OBSERVACIONES) VALUES (1,'daniel','primer insert');